.\" $Id: nedit.man,v 1.3 2001/02/26 23:38:02 edg Exp $
.TH NEDIT 1
.SH NAME
NEdit \- Text Editor
.SH SYNOPSYS
.B nedit [\-read] [\-create] [\-line\ n\ |\ +n] [\-server]
 [\-do\ command] [\-tags\ file] [\-tabs\ n] [\-wrap]
 [\-nowrap] [\-autowrap] [\-autoindent] [\-noautoindent]
 [\-autosave] [\-noautosave] [\-lm languagemode] [\-rows\ n]
 [\-columns\ n] [\-font\ font] [\-geometry\ geometry]
 [\-iconic] [\-noiconic] [\-display\ [host]:server[.screen]
 [\-xrm\ resourcestring] [\-svrname\ name] [-import file]
 [\-background color] [\-foreground color] [file...]
.SH DESCRIPTION
NEdit is a GUI style editor for plain text files.  It provides mouse based
editing and a streamlined editing style, based on popular Macintosh and MS
Windows editors, for users of X workstations and X terminals.  
.PP
NEdit requires an X-based workstation or X-Terminal.  If you
have used telnet or rlogin to access the host Unix system, set
the Unix environment variable for your display:
.PP
.B % setenv DISPLAY devicename:0
.PP
For more information see NEdit's on-line help, or nedit.doc in the
NEdit distribution kit.
.SH SEE ALSO
nc, X, mwm, vi, emacs
