# $Id: Makefile.linux,v 1.2 2001/02/26 23:38:03 edg Exp $
CC=cc
AR=ar

# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
CFLAGS=-O -I/usr/lesstif/include -I/usr/X11R6/include -DUSE_DIRENT -DUSE_LPR_PRINT_CMD
ARFLAGS=-urs
LIBS= -L/usr/lesstif/lib -L/usr/X11R6/lib -lm -lXm -lXpm -lXext -lXt -lSM -lICE -lX11

include Makefile.common
