# $Id: Makefile.convex,v 1.3 2001/08/17 23:02:55 edg Exp $
# Makefile for Convex
#
# Thanks to Stephane Bortzmeyer, Conservatoire National des Arts et Metiers
CC=/bin/cc
AR=/bin/ar
ARFLAGS = ur
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS= -O3 -nv
LIBS= -L/usr/lib/X11 -lXm -lXt -lX11
include Makefile.common
