# $Id: Makefile.unicos,v 1.2 2001/02/26 23:38:03 edg Exp $
# Makefile for Cray Unicos
#
# Thanks to Osman Buyukisik
CC=cc
AR=ar
CFLAGS=-O -DUSE_DIRENT -DUNICOS
BIGGER_STRINGS=
LIBS=  -lXm -lXt -lX11 -lm

include Makefile.common
