#
# $Id: Makefile.superux,v 1.2 2001/06/09 18:48:44 amai Exp $
# NEdit Makefile for NEC SUPER-UX
#
# CC=/bin/cc
# CC=/usr/bin/cc
CC=cc
AR=ar
# 
# The -hansi flag forces ANSI compilation, even 
# though ANSI should be the compiler default anyway
#
CFLAGS=-O -hansi -DUSE_DIRENT -DUSE_MOTIF_GLOB
ARFLAGS=-urs
BIGGER_STRINGS=
LIBS=-lm -lXm -lXt -lX11 -lSM -lICE -lgen

include Makefile.common
