# $Id: Makefile.uhc,v 1.4 2002/09/26 10:01:34 ajhood Exp $
# Makefile for UHC Unix
#
# Thanks to peter@stella.nmti.co
CC=/usr/ucb/cc
AR=ar
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
# To test if the Motif library exports the runtime version
# add -DHAVE__XMVERSIONSTRING to CFLAGS
#
CFLAGS=-O
LIBS=-lm -lXm -lXt -lX11 -lgen

include Makefile.common
