# $Id: Makefile.dec,v 1.3 2001/06/09 18:48:44 amai Exp $
#
# Makefile for old versions of OSF.
# Use Makefile.dec for Digital Unix 4.0 and above
#
CC=cc
AR=ar
CFLAGS=-O -DUSE_DIRENT
ARFLAGS=-urs
BIGGER_STRINGS= -Wf,-XNl8192
LIBS= -lXm -lXt -lX11 -lm

include Makefile.common
