# $Id: Makefile.lynx,v 1.2 2001/02/26 23:38:03 edg Exp $
CC=cc
AR=ar

# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
CFLAGS=-O -I/usr/X11R6/include -DUSE_DIRENT -DUSE_LPR_PRINT_CMD -DDONT_HAVE_GLOB -Dlinux
LIBS= -L/usr/lib -lm -lXm -lXpm -lXext -lXt -lSM -lICE -lX11 -lbsd

include Makefile.common
