# $Id: Makefile.unicos,v 1.4 2001/08/17 23:02:55 edg Exp $
# Makefile for Cray Unicos
#
# Thanks to Osman Buyukisik
CC=cc
AR=ar
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=-O -DUSE_DIRENT -DUNICOS
BIGGER_STRINGS=
LIBS=  -lXm -lXt -lX11 -lSM -lICE -lm

include Makefile.common
