# $Id: Makefile.reliant,v 1.3 2001/08/17 23:02:55 edg Exp $
#Makefile for ReliantUNIX-N Version 5.44 (SINIX)
CC=cc
AR=ar
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=-O -DUSE_DIRENT
LIBS=-L/usr/lib/netlib -lm -lXm -lXpm -lXext -lXt -lSM -lICE -lX11 -lsocket -lns
l -ltcpip -lstraddr -lnsl

include Makefile.common
