# $Id: Makefile.uhc,v 1.2 2001/02/26 23:38:03 edg Exp $
# Makefile for UHC Unix
#
# Thanks to peter@stella.nmti.co
CC=/usr/ucb/cc
AR=ar
CFLAGS=-O
LIBS=-lm -lXm -lXt -lX11 -lgen

include Makefile.common
