# $Id: Makefile.uhc,v 1.3 2001/08/17 23:02:55 edg Exp $
# Makefile for UHC Unix
#
# Thanks to peter@stella.nmti.co
CC=/usr/ucb/cc
AR=ar
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=-O
LIBS=-lm -lXm -lXt -lX11 -lgen

include Makefile.common
