# $Id: Makefile.unixware,v 1.3 2001/08/17 23:02:55 edg Exp $
CC=/usr/ccs/bin/cc
AR=ar
# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=-O -I/usr/X/include -DUSE_DIRENT -DROWCOLPATCH

LIBS= -L/usr/X/lib -lm -lXm -lXt -lX11 -lgen -lnsl

include Makefile.common
