# $Id: Makefile.dcosx,v 1.3 2001/08/17 23:02:55 edg Exp $
# Makefile for Pyramid
#
# Thanks to Koen D'Hondt and patrick@wombat.logica.co.uk
CC=cc
AR=ar
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=-O
LIBS= -lXm -lXt -lX11

include Makefile.common
