# $Id: Makefile.unicos,v 1.3 2001/04/14 09:51:30 amai Exp $
# Makefile for Cray Unicos
#
# Thanks to Osman Buyukisik
CC=cc
AR=ar
CFLAGS=-O -DUSE_DIRENT -DUNICOS
BIGGER_STRINGS=
LIBS=  -lXm -lXt -lX11 -lSM -lICE -lm

include Makefile.common
