# $Id: Makefile.ultrix,v 1.3 2001/08/17 23:02:55 edg Exp $
CC=cc
AR=ar
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=-O -DUSE_MOTIF_GLOB
ARFLAGS=-urs
BIGGER_STRINGS= -Wf,-XNl8192
LIBS=-lm -lXm -lXt -lX11

include Makefile.common
