# $Id: Makefile.cygwin,v 1.3 2001/02/26 23:38:03 edg Exp $
CC=gcc
AR=ar

# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
CFLAGS=-O -I/usr/X11R6.4/include -DDONT_HAVE_GLOB -DCYGWIN -DUSE_DIRENT -DUSE_LPR_PRINT_CMD -DNO_XMIM
ARFLAGS=-urs
LIBS= -L/usr/X11R6.4/lib -lXm -lXpm -lXext -lXt -lSM -lICE -lX11

include Makefile.common
