# $Id: Makefile.convex,v 1.2 2001/02/26 23:38:03 edg Exp $
# Makefile for Convex
#
# Thanks to Stephane Bortzmeyer, Conservatoire National des Arts et Metiers
CC=/bin/cc
AR=/bin/ar
ARFLAGS = ur
CFLAGS= -O3 -nv
LIBS= -L/usr/lib/X11 -lXm -lXt -lX11
include Makefile.common
