# $Id: Makefile.dec,v 1.4 2001/08/17 23:02:55 edg Exp $
#
# Makefile for old versions of OSF.
# Use Makefile.dec for Digital Unix 4.0 and above
#
CC=cc
AR=ar
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=-O -DUSE_DIRENT
ARFLAGS=-urs
BIGGER_STRINGS= -Wf,-XNl8192
LIBS= -lXm -lXt -lX11 -lm

include Makefile.common
