# $Id: Makefile.dcosx,v 1.2 2001/02/26 23:38:03 edg Exp $
# Makefile for Pyramid
#
# Thanks to Koen D'Hondt and patrick@wombat.logica.co.uk
CC=cc
AR=ar
CFLAGS=-O
LIBS= -lXm -lXt -lX11

include Makefile.common
