# $Id: Makefile.unixware,v 1.4 2001/10/21 15:09:42 tringali Exp $
CC=/usr/ccs/bin/cc
AR=ar
# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=-O -I/usr/X/include -DUSE_DIRENT -DROWCOLPATCH

LIBS= -L/usr/X/lib -lXm -lXt -lX11 -lSM -lICE -lgen -lnsl -lm

include Makefile.common
