# $Id: Makefile.sunos,v 1.3 2001/08/17 23:02:55 edg Exp $
CC=/usr/lang/acc
AR=/usr/5bin/ar
# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=-O -DSUNOS -DUSE_LPR_PRINT_CMD -DUSE_MOTIF_GLOB
ARFLAGS=-urs
LIBS= -lm -Bstatic -lXm -lXt -lX11

include Makefile.common
