# $Id: Makefile.osf,v 1.4 2001/08/17 23:02:55 edg Exp $
#
# Makefile for nirvana utilities 
#    OSF/1 version: Digital Unix >=4.0, Tru64
#
CC=cc
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=$(DEBUG) -DUSE_DIRENT -DFUNCPROTO -DXTFUNCPROTO
LIBS= -lXm -lXt -lX11 -lm
NLIBDIR = ../osf_lib
NBINDIR = ../osf_bin
MAKEDEPEND=makedepend -Y

include Makefile.common
