# $Id: Makefile.osf,v 1.2 2001/02/26 23:38:03 edg Exp $
#
# Makefile for nirvana utilities (OSF/1 version)
#
CC=cc
CFLAGS=$(DEBUG) -DUSE_DIRENT -DFUNCPROTO -DXTFUNCPROTO
LIBS=-lm -lXm -lXt -lX11
NLIBDIR = ../osf_lib
NBINDIR = ../osf_bin
MAKEDEPEND=makedepend -Y

include Makefile.common
