# $Id: Makefile.freebsd,v 1.3 2001/08/17 23:02:55 edg Exp $
CC=cc
AR=ar

# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
CFLAGS=-O -I${PREFIX}/include -DUSE_DIRENT -DUSE_LPR_PRINT_CMD -DUSE_XMIM
LIBS= ${MOTIFLIB} -L${PREFIX}/lib -lm -lXpm -lXext -lXt -lSM -lICE -lX11

include Makefile.common
