/* $Id: help.h,v 1.3 2001/02/26 23:38:03 edg Exp $ */
enum HelpTopic {HELP_VERSION, HELP_START, HELP_SEARCH, HELP_SELECT,
	HELP_CLIPBOARD, HELP_INDENT, HELP_TABS, HELP_PROGRAMMER, HELP_TAGS,
	HELP_MOUSE, HELP_KEYBOARD, HELP_FILL, HELP_FORMAT, HELP_SYNTAX,
	HELP_RECOVERY, HELP_PREFERENCES, HELP_SHELL, HELP_REGEX_BASICS,
	HELP_REGEX_ESC_SEQ, HELP_REGEX_PAREN, HELP_REGEX_ADV,
	HELP_REGEX_EXAMPLE, HELP_COMMAND_LINE, HELP_SERVER, HELP_CUSTOMIZE,
	HELP_RESOURCES, HELP_BINDING, HELP_LEARN, HELP_MACRO_LANG,
	HELP_MACRO_SUBRS, HELP_ACTIONS, HELP_PATTERNS, HELP_SMART_INDENT,
	HELP_BUGS, HELP_MAILING_LIST, HELP_DISTRIBUTION, HELP_TABS_DIALOG};
#define NUM_TOPICS 37

void Help(Widget parent, enum HelpTopic topic);
