# SCCS ID: Makefile.osf 1.1 3/4/94
#
# Makefile for nirvana utilities (OSF/1 version)
#
CC=cc
CFLAGS=$(DEBUG) -DUSE_DIRENT -DFUNCPROTO -DXTFUNCPROTO
LIBS=-lm -lXm -lXt -lX11
NLIBDIR = ../osf_lib
NBINDIR = ../osf_bin
MAKEDEPEND=makedepend -Y

include Makefile.common
