/* $Id: userCmds.h,v 1.3 2001/02/26 23:38:03 edg Exp $ */
void EditShellMenu(WindowInfo *window);
void EditMacroMenu(WindowInfo *window);
void EditBGMenu(WindowInfo *window);
void UpdateShellMenu(WindowInfo *window);
void UpdateMacroMenu(WindowInfo *window);
void UpdateBGMenu(WindowInfo *window);
char *WriteShellCmdsString(void);
char *WriteMacroCmdsString(void);
char *WriteBGMenuCmdsString(void);
int LoadShellCmdsString(char *inString);
int LoadMacroCmdsString(char *inString);
int LoadBGMenuCmdsString(char *inString);
int DoNamedShellMenuCmd(WindowInfo *window, char *itemName, int fromMacro);
int DoNamedMacroMenuCmd(WindowInfo *window, char *itemName);
int DoNamedBGMenuCmd(WindowInfo *window, char *itemName);
void SetBGMenuUndoSensitivity(WindowInfo *window, int sensitive);
void SetBGMenuRedoSensitivity(WindowInfo *window, int sensitive);
void DimSelectionDepUserMenuItems(WindowInfo *window, int sensitive);
void DimPasteReplayBtns(int sensitive);
